<?php
  $apiKey="rzp_test_pZBd9rupmqsXga";
?>

<form action="#" method="POST">
    <script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $apiKey; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="<?php echo $_POST['amount']*100; ?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data_id="<?php 'OID'.rand(10,100).'END'; ?>"// Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with Razorpay"
    data-name="Myntra Corporation"
    data-description="Best website for shopping Clothes!"
    data-image="https://i0.wp.com/logotaglines.com/wp-content/uploads/2016/10/Myntra-New-Logo-Tagline-offensive-controversy.jpg?zoom=2&resize=370%2C297&ssl=1"                 //Missing logo
    data-prefill.name="<?php echo $_POST['Name']; ?>"
    data-prefill.email="<?php echo $_POST['Email']; ?>"
    data-prefill.contact="<?php echo $_POST['Mobile']; ?>"
    data-theme.color="#F37254"
    ></script>
    <input type="hidden" custom="Hidden Element" name="hidden"/>
</form>